### PR TITLE
Update benchmark.cpp

### PR DESCRIPTION
**Pull request by Sarthak-9**
Suggested a new header file

### CODE REVIEW

**Comment by DHowett** [comment]
I'm not certain it's appropriate to include things in the bits directory. Isn't it a GCC/glibc/libstdc++ implementation detail? I haven't seen it with other libraries or compilers.

**Comment by kimwalisch** [comment]
> Suggested a new header file

What is it used for?

**Comment by Sarthak-9** [comment]
It is basically a header file that includes every standard library. If you are working with any GCC compiler you can use this in place of header files for string, vectors etc. This header file is also handy for competitive programming.

**Comment by kimwalisch** [comment]
Rejected: Spam pull request

**Pull request closed without merging**
